services:
  - type: web
    name: csu-halal-bot
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DAILY_SEND_HOUR
        value: "7"
      - key: DAILY_SEND_MINUTE
        value: "0"
      - key: TIMEZONE
        value: America/Denver
      - key: USE_WEBHOOK
        value: "true"
